### ISSUE TITLE
【开源之道Talking】“我是来学习的”是一种什么样的参与开源心态？

### ISSUE THREAD

**Issue by lijiangsheng1** [OCselected/ttoos#170]
在贡献中学习，我们是学习共同体。

>我经常遇到来关注开源的朋友是这么表达的：
>我还是刚接触，初学者，我是来学习的。
>大多这样的人在群里都是潜水🤿这样的人占90%之多。

是如何做到心安理得的去参与到一个自组织的团体当中的？

Learning by doing! 还有很长的路要走！

**Comment by wangleo61** [comment]
Doing something

**Comment by lijiangsheng1** [comment]
2021.8.19 日录制完成。
