### ISSUE TITLE
[Podcast] 播客内容改进建议

### ISSUE THREAD

**Issue by frank-zsy** [OCselected/ttoos#192]
例如此类播客：http://opensourceway.community/posts/opensource_talking/2020-02-02-open-source-developer/ ，是否可以以文字形式提供参与讨论人的信息，似乎在这期中文字和音频中都没有介绍参与人的信息。

**Comment by lijiangsheng1** [comment]
感谢反馈～ 

这期应该是年三十，欧建深、庄表伟和我，不睡觉开聊的。我尽快补上～
