### ISSUE TITLE
【开源之道Talking】【永雷Host】开源世界的Diversity探讨

### ISSUE THREAD

**Issue by wangleo61** [OCselected/ttoos#195]
Diversity，多样性和包容性，在开源的精彩世界里，让我们一起来探究多样性的魅力

**Comment by wangleo61** [comment]
邀请嘉宾： 振华-开源世界  ，儒雅型学者
                  Richard Lin -开源界前辈，大咖

**Comment by wangleo61** [comment]
暂定日期： 2020年9月26日 21:00 -22:00

**Comment by lijiangsheng1** [comment]
https://opensource.com/article/20/9/open-source-role-diversity

https://podcast.chaoss.community/

均有很好的描述，可以借鉴一番。另外《the Difference》等圣塔菲书系更加值得参考来。

**Comment by wangleo61** [comment]
开源之道 is inviting you to a scheduled Zoom meeting.

Topic: 开源之道Talking：开源世界的Diversity探讨
Time: Sep 27, 2020 09:00 PM Beijing, Shanghai

Join Zoom Meeting
https://zoom.com.cn/j/61112202060?pwd=SkdzZXlxM1JYSlhva212SjdoRkRRZz09

Meeting ID: 611 1220 2060
Passcode: 238637
One tap mobile
+12532158782,,61112202060#,,,,,,0#,,238637# US (Tacoma)
+13017158592,,61112202060#,,,,,,0#,,238637# US (Germantown)

Dial by your location
        +1 253 215 8782 US (Tacoma)
        +1 301 715 8592 US (Germantown)
        +1 312 626 6799 US (Chicago)
        +1 346 248 7799 US (Houston)
        +1 646 558 8656 US (New York)
        +1 720 707 2699 US (Denver)
        +1 8186657236(Voxbone) US (Los Angeles)
Meeting ID: 611 1220 2060
Passcode: 238637
Find your local number: https://zoom.com.cn/u/i9h6hsy96
