### ISSUE TITLE
【开源之播】【永雷Host】ISO/IEC 5230:2020 and OpenChain 2.0.

### ISSUE THREAD

**Issue by wangleo61** [OCselected/ttoos#220]
缘起：
随着开源的兴起，开源供应链管理变得越来越重要，在2020年快要结束的时候，我们迎来了ISO/IEC 5230:2020，开源供应链的国际标准，我们的企业应该如何应对，我们应该如何去理解这样的一个标准，在新的一年，我们来聊聊吧

https://mp.weixin.qq.com/s/epdU_pkqyiSCWhaIrFoGdw
开放原子副主席谭中意分享
SZ lin的分享

https://szlin.me/2019/08/24/openchain-2-0-合規且有效使用-open-source-software/

**Comment by wangleo61** [comment]
参与人：振华，永雷，待邀请更多

**Comment by wangleo61** [comment]
Yong-Lei Wang is inviting you to a scheduled Zoom meeting.  
Topic: OpenChain  ISO/IEC 5230:2020 Time: Jan 1, 2021 08:00 PM Beijing, Shanghai  
Join Zoom Meeting https://synopsys.zoom.us/j/97282830166?pwd=Zmp2ZWtzbk1wRXpvWFlmemk0RUJSQT09  
Meeting ID: 972 8283 0166 Passcode: cN4Y%YWd 
One tap mobile +13126266799,,97282830166#,,,,,,0#,,70416317# US (Chicago) +13462487799,,97282830166#,,,,,,0#,,70416317# US (Houston)

**Comment by king-gao** [comment]
感兴趣

**Comment by wangleo61** [comment]
Hi King,

Welcome join

BR

Leo


发件人: king<mailto:notifications@github.com>
发送时间: Thursday, December 31, 2020 5:01 PM
收件人: OCselected/ttoos<mailto:ttoos@noreply.github.com>
抄送: wangleo61<mailto:wangleo61@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [OCselected/ttoos] 【开源之播】【永雷Host】ISO/IEC 5230:2020 and OpenChain 2.0. (#220)


感兴趣

―

**Comment by wangleo61** [comment]
Open Chain的起源?
Open Chain的ISO ISO/IEC 5230:2020 and OpenChain 2.1
ISO/IEC 5230:2020 and OpenChain 2.0 和ISO/IEC 5230:2020 and OpenChain 2.1的区别
如何去理解ISO/IEC 5230:2020 and OpenChain 2.1

**Comment by will-ww** [comment]
一起一起~

**Comment by wangleo61** [comment]
Warmly welcome.

Leo

发件人: Will Wang<mailto:notifications@github.com>
发送时间: Friday, January 1, 2021 7:42 PM
收件人: OCselected/ttoos<mailto:ttoos@noreply.github.com>
抄送: wangleo61<mailto:wangleo61@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [OCselected/ttoos] 【开源之播】【永雷Host】ISO/IEC 5230:2020 and OpenChain 2.0. (#220)


一起一起~

―

**Comment by wangleo61** [comment]
About the OpenChain Project

The OpenChain Project builds trust in open source by making open source license compliance simpler and more consistent. The OpenChain Specification defines a core set of requirements every quality compliance program must satisfy. The OpenChain Curriculum provides the educational foundation for open source processes and solutions, whilst meeting a key requirement of the OpenChain Specification. OpenChain Conformance allows organizations to display their adherence to these requirements. The result is that open source license compliance becomes more predictable, understandable and efficient for participants of the software supply chain.

关于OpenChain项目

OpenChain项目通过使开放源代码许可证合规性更加简单和一致来建立对开放源代码的信任。 OpenChain规范定义了每个质量合规程序必须满足的一组核心要求。 OpenChain课程为开源流程和解决方案提供了教育基础，同时满足了OpenChain规范的关键要求。 OpenChain Conformance允许组织显示对这些要求的遵守情况。 结果是，对于软件供应链的参与者而言，开源许可证合规性变得更加可预测，可理解和高效。

**Comment by wangleo61** [comment]
Reasons to Engage
The OpenChain Project is designed to be useful and adoptable for all types of entities in the supply chain. As such, it is important to distill its value proposition for various potential partners. Our volunteer community created a list of five practical reasons to engage:

OpenChain makes free and open source software (FOSS) more accessible to your developers. OpenChain provides a framework for shared, compliant use of FOSS. Conforming companies create an environment that supports use of FOSS internally and sharing of FOSS with partners.
OpenChain reduces overall compliance effort, saving time and legal and engineering resources. OpenChain allows companies in a supply chain to work together toward FOSS compliance and provides a consistent standard to which all must perform. By contrast, in a typical supply chain, each member of the chain has to perform FOSS compliance for software of others in the chain, wasting time and resources in a duplication of effort.
OpenChain may be adapted to your existing systems. OpenChain allows you to choose your own processes to meet its requirements. OpenChain provides resources that help you design new processes from the ground up, or you may choose to use the systems you have in place.
OpenChain helps your business teams work together toward a common goal. OpenChain provides a blueprint for your legal, engineering, and business teams to work together toward FOSS compliance.
OpenChain allows you to conform to a stable, community-backed specification. When you adopt OpenChain, you conform to a stable specification that is widely backed by industry and community participants. OpenChain was developed in an open, collaborative process, with contributors from a wide range of industries across Asia, Europe and North America. OpenChain is being formally adopted by a growing number of both small and larger companies.
Today, the OpenChain Project is addressing its goals and moving towards wider market adoption with the support of 14 Platinum members: Adobe, Arm, Cisco, Comcast, GitHub, Harman, Hitachi, HPE, Qualcomm, Siemens, Sony, Toyota, Western Digital, and Wind River. The project also has a broad community of volunteers helping to make open source compliance easier for a multitude of market segments. As we move into 2018, the OpenChain Project is well positioned for adoption by Tier 1, Tier 2, and Tier 3 suppliers in multiple sectors, ranging from embedded to mobile to automotive to enterprise to infrastructure.

Entities of all sizes are welcome to participate in the OpenChain Project. Everyone is welcome and encouraged to join our mailing list at:

https://lists.linuxfoundation.org/mailman/listinfo/openchain

You can also send private email to the Project Director, Shane Coughlan, at coughlan@linux.com.

**Comment by wangleo61** [comment]
https://www.openchainproject.org/get-started/conformance

**Comment by wangleo61** [comment]
zhenhua: 大公司交付的合同，合规要求比较高的公司，和开源相关的，律师的介绍，openChain ,合规

**Comment by wangleo61** [comment]
坤少，最早接触这个项目，06年毕业，深航工作，11年进的华为，2014做开源的工作，OPSO,其他的大厂，开源管理，大家最好，法务开始做起，license,是非常重要的，对于知识产权的尊重，对于法律的尊重，希望的法律，都是以条文来约束大家的行动，开源的license非常多，开源的License可以任意的定义，分析openchain, 2016接触开源项目，日本东京举办的open source compliance, 日本企业推广openchain, 中国的企业也在推广，openchain的翻译，中文和日文和韩文，深入了解了openchain,  中国96%的企业可能不太到位，国内的环境原因，这方面的诉讼不太多，ISO的推广，全世界很多的国家都通过了，OpenChain 2020 06 OPPO 成为白金会员，中国企业想出海，想做大产业链，全产业链都需要

**Comment by wangleo61** [comment]
14年开始做开源相关的，懂法律的，专利makhadit,a IT table的文件，运行商捆绑销售，德电，中国没有相关的知识产权的律师，Richard 林

**Comment by wangleo61** [comment]
王老师：openChain, 高校会从研究的背景，CHAOSS, 中科院的吴艳君老师，开源点亮计划，最近也发布了，2021发布供应链的报告，王老师也会数据方面的支持，数据分析，数据追踪

**Comment by wangleo61** [comment]
比较好的，openchain,2.1，规则文本

**Comment by wangleo61** [comment]
和compliance不同，openchain sumit, openchain, 形成标准和研究方向，container和serverless, 所有的包，openchain, dependeance, sonatype, maven,npm, pip,pypy, go mode, 工具仓之间的compliance 的传导性，这两年会做一些推广和标准化

**Comment by wangleo61** [comment]
帮助企业帮助解决具体的场景，比如依赖和OSPO，

**Comment by wangleo61** [comment]
20:53:55	 From 高琨 : https://www.oschina.net/news/123147/open-source-license-compatibility-guide
20:59:06	 From 振华 : https://github.com/OpenChain-Project/Specification/tree/master/Official/zh-Hans
20:59:17	 From 振华 : 以上是github下载的
21:06:28	 From Yong-Lei Wang : OpenChain Conformance allows organizations to display their adherence to these requirements
21:15:03	 From 高琨 : https://todogroup.org/
21:15:09	 From 振华 : 对
21:15:13	 From Yong-Lei Wang : 收到
21:15:33	 From 振华 : todo group也有对应的github

**Comment by king-gao** [comment]
建议可以把大家的keypoint做成文章或者宣传之类的，这样子传播性会更好一点。

**Comment by chaojie99** [comment]
Surprise ! Sparks of fire can start a prairie fire!

**Comment by wangleo61** [comment]
welcome join

获取 Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by wangleo61** [comment]
> 建议可以把大家的keypoint做成文章或者宣传之类的，这样子传播性会更好一点。

好主意

**Comment by wangleo61** [comment]
> Surprise ! Sparks of fire can start a prairie fire!

thanks Chaojie, looking forward your join.
