### ISSUE TITLE
【开源之播】【永雷Host】How OpenChain and ISO 5230 adopt to enterprise customer 

### ISSUE THREAD

**Issue by wangleo61** [OCselected/ttoos#231]
随着OpenChain 2.1新的版本成为ISO/IEC 5230的国际标准，引起了越来越多的行业和企业的关注，那么从企业的角度来，ISO/IEC 5230可以给企业带来什么样的价值，如果企业想获得认证，需要做什么样的准备，针对这些问题，
我们这次邀请了OpenChain团队的资深专家来一起聊聊

With the new version of openchain 2.1 becoming the international standard of ISO / IEC 5230, more and more industries and enterprises are paying attention to it. From the perspective of enterprises, what kind of value can ISO / IEC 5230 bring to enterprises? If enterprises want to obtain certification, what kind of preparation should they make? In order to solve these problems,

We invited senior experts from the openchain team to have a chat

**Comment by wangleo61** [comment]
Guest: 
ZhongYi Tan: OpenAtom TOC Member, Open Source Expert
Shane Coughlan: OpenChain GM @Linuxfoundation. Assembly Member
ZhenHua Sun: Bytedance IP expert
JianSheng Li: He is the founder of Kuo Si, the Open Source evangelist of APAC of Linux foundation, a member of Apache local community Beijing, and a member of the education group of the Executive Committee of Open Source society.
In 2020, it will be rated as "33 pioneers of China's open source" by Sifu and Kaiyuan society.
Host: 
Leo Wang, Synospsy Open-source Governance expert

**Comment by wangleo61** [comment]
Yong-Lei Wang is inviting you to a scheduled Zoom meeting.

Topic: How OpenChain and ISO 5230 help to enterprise customer 
Time: Feb 13, 2021 08:00 AM Beijing, Shanghai

Join Zoom Meeting
https://synopsys.zoom.us/j/2867026076?pwd=SWxpQzhINUwyeldmZFF6RTVtK3Y1Zz09

Meeting ID: 286 702 6076
Passcode: @EhwZpQ2
One tap mobile
+16465588656,,2867026076#,,,,,,0#,,86657476# US (New York)
+16699006833,,2867026076#,,,,,,0#,,86657476# US (San Jose)

Dial by your location
        +1 646 558 8656 US (New York)
        +1 669 900 6833 US (San Jose)
        +1 253 215 8782 US (Tacoma)
        +1 301 715 8592 US (Washington DC)
        +1 312 626 6799 US (Chicago)
        +1 346 248 7799 US (Houston)
        833 548 0276 US Toll-free
        833 548 0282 US Toll-free
        877 853 5247 US Toll-free
        888 788 0099 US Toll-free
        +82 2 6022 2322 Korea, Republic of
        +82 2 6105 4111 Korea, Republic of
        0 808 220 250 Korea, Republic of Toll-free
        +65 3158 7288 Singapore
        +65 3165 1065 Singapore
        800 101 3814 Singapore Toll-free
        800 852 6054 Singapore Toll-free
        1800 407 5602 Singapore Toll-free
        +48 22 307 3488 Poland
        +48 22 398 7356 Poland
        +48 22 306 5342 Poland
        00 800 112 5171 Poland Toll-free
        00 800 321 1464 Poland Toll-free
        00 800 012 087 Poland Toll-free
        +81 363 628 317 Japan
        +81 524 564 439 Japan
        +81 3 4578 1488 Japan
        0 120 829 768 Japan Toll-free
        0 120 836 177 Japan Toll-free
        00 663 381 4092 Japan Toll-free
        0 800 100 5040 Japan Toll-free
        +972 3 978 6688 Israel
        +972 55 330 1762 Israel
        1801 227 228 Israel Toll-free
        +353 1 653 3898 Ireland
        +353 6 163 9031 Ireland
        +353 1 240 8941 Ireland
        +353 1 536 9320 Ireland
        +353 1 653 3895 Ireland
        +353 1 653 3897 Ireland
        1800 943 965 Ireland Toll-free
        1800 949 238 Ireland Toll-free
        1800 901 561 Ireland Toll-free
        +44 203 481 5240 United Kingdom
        +44 203 901 7895 United Kingdom
        +44 208 080 6591 United Kingdom
        +44 208 080 6592 United Kingdom
        +44 330 088 5830 United Kingdom
        +44 131 460 1196 United Kingdom
        +44 203 481 5237 United Kingdom
        0 800 031 5717 United Kingdom Toll-free
        0 800 260 5801 United Kingdom Toll-free
        0 800 358 2817 United Kingdom Toll-free
        0 800 456 1369 United Kingdom Toll-free
        +91 22 48 798 004 India
        +91 224 879 8012 India
        +91 226 480 2722 India
        +91 22 71 279 525 India
        +91 406 480 2722 India
        +91 446 480 2722 India
        +91 806 480 2722 India
        +91 80 71 279 440 India
        +91 116 480 2722 India
        000 800 001 4002 India Toll-free
        000 800 050 5050 India Toll-free
        +36 1 701 0488 Hungary
        +36 1 779 9126 Hungary
        +36 1 408 8456 Hungary
        800 881 88 Hungary Toll-free
        +49 30 5679 5800 Germany
        +49 69 3807 9883 Germany
        +49 695 050 2596 Germany
        +49 69 7104 9922 Germany
        0 800 000 1590 Germany Toll-free
        0 800 000 6954 Germany Toll-free
        0 800 1800 150 Germany Toll-free
        0 800 588 9791 Germany Toll-free
        +33 1 8699 5831 France
        +33 1 7037 2246 France
        +33 1 7037 9729 France
        +33 1 7095 0103 France
        +33 1 7095 0350 France
        0 800 944 049 France Toll-free
        0 805 543 065 France Toll-free
        0 800 940 415 France Toll-free
        +1 647 558 0588 Canada
        +1 778 907 2071 Canada
        +1 204 272 7920 Canada
        +1 438 809 7799 Canada
        +1 587 328 1099 Canada
        +1 647 374 4685 Canada
        855 703 8985 Canada Toll-free
        +886 (2) 7741 7473 Taiwan
        08 0909 9864 Taiwan Toll-free
        809 070 608 Taiwan Toll-free
        +66 2018 2486 Thailand
        +66 60 003 5790 Thailand
        1 800 012 275 Thailand Toll-free
        1 800 013 864 Thailand Toll-free
        +47 2400 4735 Norway
        +47 7349 4877 Norway
        +47 2396 0588 Norway
        800 248 88 Norway Toll-free
        +351 308 804 188 Portugal
        +351 308 810 988 Portugal
        +351 211 202 618 Portugal
        800 780 052 Portugal Toll-free
        800 780 072 Portugal Toll-free
        800 210 145 Portugal Toll-free
        +31 20 794 7345 Netherlands
        +31 707 006 526 Netherlands
        +31 20 241 0288 Netherlands
        +31 20 794 0854 Netherlands
        +31 20 794 6519 Netherlands
        +31 20 794 6520 Netherlands
        0 800 025 0113 Netherlands Toll-free
        0 800 220 0040 Netherlands Toll-free
        0 800 022 1954 Netherlands Toll-free
        +358 9 4245 1488 Finland
        +358 9 7252 2471 Finland
        +358 3 4109 2129 Finland
        0 800 102 188 Finland Toll-free
        0 800 302 585 Finland Toll-free
        +56 41 256 0288 Chile
        +56 22 573 9304 Chile
        +56 22 573 9305 Chile
        +56 23 210 9066 Chile
        +56 232 938 848 Chile
        123 002 00163 Chile Toll-free
        1888 0020 1208 Chile Toll-free
        800 393 357 Chile Toll-free
        800 914 125 Chile Toll-free
        +86 10 5387 6330 China
        +86 10 8783 3177 China
        400 616 8835 China Toll-free
        400 669 9381 China Toll-free
        400 182 3168 China Toll-free
        +84 869 402 526 Viet Nam
        +84 28 4458 2373 Viet Nam
        1228 0906 Viet Nam Toll-free
        1800 400 332 Viet Nam Toll-free
        1203 2625 Viet Nam Toll-free
        +94 7 2091 0374 Sri Lanka
        112 029 070 Sri Lanka Toll-free
        +7 495 283 9788 Russian Federation
        +7 499 951 6379 Russian Federation
        +7 499 951 6380 Russian Federation
        +7 812 426 8988 Russian Federation
        8800 100 6938 Russian Federation Toll-free
        8800 301 7427 Russian Federation Toll-free (Landline)
        0800 000 9608 Egypt Toll-free
        0 800 006 0118 Egypt Toll-free
Meeting ID: 286 702 6076
Passcode: 86657476
Find your local number: https://synopsys.zoom.us/u/ajagYkNA5

Join by SIP
2867026076@zoomcrc.com

Join by H.323
162.255.37.11 (US West)
162.255.36.11 (US East)
221.122.88.195 (China)
115.114.131.7 (India Mumbai)
115.114.115.7 (India Hyderabad)
213.19.144.110 (Amsterdam Netherlands)
213.244.140.110 (Germany)
103.122.166.55 (Australia Sydney)
103.122.167.55 (Australia Melbourne)
209.9.211.110 (Hong Kong SAR)
149.137.40.110 (Singapore)
64.211.144.160 (Brazil)
69.174.57.160 (Canada Toronto)
65.39.152.160 (Canada Vancouver)
207.226.132.110 (Japan Tokyo)
149.137.24.110 (Japan Osaka)
Meeting ID: 286 702 6076
Passcode: 86657476

**Comment by wangleo61** [comment]
Topics:
1. Introduce yourself and the story with OpenChain
2. The OpenChain value for the organization from your perspective
3.  How does the organization adopt Openchain?
4.  The difference between OpenChain2.0 and OpenChain 2.1, Why there is a difference that happens?
5. What's the future of the OpenChain? 
6. How OpenChain suggested the enterprise customer face the Challenge of the opensource dependency ？

**Comment by shanecoughlan** [comment]
No one turned up for the scheduled meeting. Let's reset it for another day. I suggest next Thursday.

**Comment by wangleo61** [comment]
> No one turned up for the scheduled meeting. Let's reset it for another day. I suggest next Thursday.

thanks Shane.

**Comment by wangleo61** [comment]
> > No one turned up for the scheduled meeting. Let's reset it for another day. I suggest next Thursday.
> 
> thanks Shane.

I reschedule the meeting at Thursday 8:00 PM Beijing time.

**Comment by wangleo61** [comment]
![image](https://user-images.githubusercontent.com/62591087/108353764-78bce800-7223-11eb-9929-252a4caf1aba.png)

**Comment by wangleo61** [comment]
shane, gover open source, spend lots time copyright, global of par, GM of the openchain and open chain, this is project and should be understood, help company management the copyright, copyright, using a signal affective , compliance want to fast and cheap and easy , five years and standard iso last December, it's time

**Comment by wangleo61** [comment]
Jerry worked at openchain with Chinsese trans, openchain is great project ,give us a framework, Jerry is far is , open

**Comment by wangleo61** [comment]
bytedance, the quality of the open source ,effeicanve , really as , real changlle of the , cost , open source, based on many year of experience, openchain , it's doesn't tell you the sample of the ,bring the software into the companies, how you do that, automation, you may use the tools , you may , identify the open source ,more expense the problem , the idea is the company because we are predictable, ,openchain design for the , the big idea , , ISO standard, last year, perfect time of the co-host

**Comment by wangleo61** [comment]
tiktok, opensource component, the app client, we will identify the use mark the license and security issue, we will have the platform of the compliance work, use more than even more than 1000 components, thanks , in additional , open chain also a community, you can share the experience of the great

**Comment by wangleo61** [comment]
20 company at now as , bmw, as the tiny parts, not only for these, also has local hundred of people in mainland china, 200

**Comment by wangleo61** [comment]
the factor is most of the sector is , china company , the first time visit huawei, the quickly global is the vision of the , the vision is truly of the openchain,  seven year ago, ospo, I care about the open source compliance, I was work in the engineer effecitidnye department, I need to manamgent the open source manage more effective , I can combine this together, so I joined the openchain the group, build the Chinese

**Comment by wangleo61** [comment]
come to the openchain the community, the same project, same problem,

**Comment by wangleo61** [comment]
set the clearly of the business goal, open source openchain and , set the business goad the ,they maybe some requirement of the oversea of the , from the security department , protect the company of the company infrasturuce, make the recorded the repair the quick also you can adop the devops team, you need build the quilicy in, the tools should be as the plugin in the pipeline, you can work with legal, seuciryt, if the the company has the own ,

**Comment by wangleo61** [comment]
such as tools , you can go to the  community and get the best practise of the , the openchian is very popular in China, he drive the open openchain

**Comment by wangleo61** [comment]
how to driven the opensource, osrc, in pratise, we ofen say also management by IP department, toyota, manamgent the openchain , augest Jan, CTO office, It's really which part of the companies of the , openchain is the hight level of the guidance, you can talk with bmw, It's does not, Dpes to cover the openchain the open source security risk, many , at moment, this year, basically ,

**Comment by wangleo61** [comment]
openchain is the process, I have done you don't need any more, you don't need more, you just combine , to enforce, every engineer is open source what they used, where the

**Comment by wangleo61** [comment]
lots of time opensource compliance, little time go to the market, we these come , management the open source risk effective business compact these possible , so many company ,export control , no matter what you are doing, this is problelb,e
