### ISSUE TITLE
【开源之道Talking】六月："Peer Review" in Open Source Community /Project

### ISSUE THREAD

**Issue by lijiangsheng1** [OCselected/ttoos#50]
## 缘由
peer review 在没有开源共同体的情况下如何成为可能？peer review 是开源共同体的重要因素？
来自鼠年话开源中引出的话题，由吴晟老师和姜宁老师持不同意见而定。

## 拟邀请嘉宾：
   姜宁、周明辉
## 话题列表：
1. 什么是 Peer review ?
2. 传统学术共同体中，Peer Review 为何很重要？在科研中占据一个什么样的位置？
3. 在软件开发过程中表现为：code review、proprsal review、document review、test feedback etc. 
4. 如果仅仅是消费者社团的话，Peer review 如何成为可能？
5. 开源Community 中如何倡导 Peer Review？ Meritocracy or Democracy or absolutely equal？
6. 任何人都可以reivew？
7.  学术上的peer review 能否接受公开的评论？

## 形式

Zoom 远程

**Comment by WillemJiang** [comment]
Zoom的大概时间还有我们需要准备什么？

**Comment by lijiangsheng1** [comment]
正在邀请嘉宾中。

**Comment by lijiangsheng1** [comment]
3月 邀请周明辉老师，没有得到回复，只有无限期的等待了，或者其它熟悉学术论文和评审过程的同仁来聊了。该期节目暂时搁置，直到有人响应。

另外可以阅读的材料：

* https://en.wikipedia.org/wiki/Software_peer_review
* https://en.wikipedia.org/wiki/Peer_review

**Comment by lijiangsheng1** [comment]
公开的Peer Review 的另外一面，会带来剽窃者、搭便车者的方便，这些人是否也应归为Peer?能否这么区分？

毕竟大多数人是认为不公平的。因为抄袭是非常伤害人的事情。

**Comment by lijiangsheng1** [comment]
怎么获得Peer review？ 有人提出来的是：Offer to review someone else’s work in exchange for their review， 这非常契合孔子提出的：

子贡曰：“如有博施于民而能济众，何如？可谓仁乎？”子曰：“何事于仁，必也圣乎！尧舜其犹病诸！夫仁者，己欲立而立人，己欲达而达人。能近取譬，可谓仁之方也已。”一一（《论语·雍也》）

只是这个立要限定到具体的产业当中，具体的匠艺，具体的科学研究，同行当中。

**Comment by lijiangsheng1** [comment]
Peer 其实在现代的分工下，人与人之间的交流是非常难得，有一种能够被理解和体会的感觉，而这股力量通过互联网而整合起来，确实是开源的一大优势。也代表着未来。

**Comment by WillemJiang** [comment]
开源社区的影响力与Peer review之间的关系是怎么样的？
