### ISSUE TITLE
[讨论] 对于翻译线索是否可以添加help wanted 标签

### ISSUE THREAD

**Issue by WillemJiang** [OCselected/ttoos#73]
对于这些文章的翻译可以发动社区的力量，同时加上相关的编辑，review机制，让更多的同学参与进来共同提高对开源之道的理解。

**Comment by lijiangsheng1** [comment]
> 对于这些文章的翻译可以发动社区的力量，同时加上相关的编辑，review机制，让更多的同学参与进来共同提高对开源之道的理解。

Hi，Willem ，这个主意太好了！ 你直接添加就OK了。

**Comment by WillemJiang** [comment]
我还没有权限加标签。
