### ISSUE TITLE
【开源之道Talking】4月：开源项目的定量和定性分析—— 以CHAOSS 为例

### ISSUE THREAD

**Issue by lijiangsheng1** [OCselected/ttoos#79]
衡量的文化对于人类来说已经是离不开了，随着对自己的了解和对各种技术的掌握，人们对于确定性的事情越来越痴迷，从制造一块肥皂，到管理一家公司，无一不希望将所有的事情量化，然后再来评估人本身。开源尽管以其20多年来的实践证明自身是一套进化的系统，但是人们并没有放弃对其工程化的希望。那么如果将开源工程化的话，有哪些因素能够量化出来了呢？

这是一个迷人的话题。你要来聊吗？

开源之道Talking 四月话题，嘉宾召集中！报名直接回复该issue即可。

**Comment by ZoomQuiet** [comment]
是也乎,(￣▽￣)

俺糟想吐, 前排报名

**Comment by WillemJiang** [comment]
最近一直都研究CHAOSS项目，报名，算我一个。

**Comment by king-gao** [comment]
感兴趣，报个名。

**Comment by nicememory** [comment]
感兴趣，报个名。

**Comment by lijiangsheng1** [comment]
5位了，可以组一句了。届时我会发出Zoom 链接。

4月25日，晚上21:00~~ 22:00 如何？ 

在这之前请各位提前学习：https://chaoss.community/ 上关于衡量项的内容。并在此跟进相关问题。

期待！

**Comment by king-gao** [comment]
是否可以早一点？因为内容比较多，咱们可以分几次讨论？如何？

--------------------------------------------------
高琨 Gao Kun
Mobile: +86-15986646117<tel:+86-15986646117>
Email: king.gao@huawei.com<mailto:king.gao@huawei.com>

发件人：适兕 <notifications@github.com>
收件人：OCselected/ttoos <ttoos@noreply.github.com>
抄 送：Gaokun (King) <king.gao@huawei.com>;Comment <comment@noreply.github.com>
时 间：2020-03-31 16:26:21
主 题：Re: [OCselected/ttoos] 【开源之道Talking】4月：开源项目的定量和定性分析—— 以CHAOSS 为例 (#79)


5位了，可以组一句了。届时我会发出Zoom 链接。

4月25日，晚上21:00~~ 22:00 如何？

在这之前请各位提前学习：https://chaoss.community/ 上关于衡量项的内容。并在此跟进相关问题。

期待！

**Comment by WillemJiang** [comment]
由于Talking讨论的的目的是通过对CHAOSS的介绍，让更多的人入坑。
@king-gao 建议把你关注的问题列一下，我们可以在issue里面讨论起来。 

个人感觉CHAOSS涵盖的内容比较多， 五个工作组研究的侧重点都不一样，建议大家选择自己关注的方向简单阐述一下对CHAOSS 工作的认识以及自己的关注点。 这些可以成为我们Talking的主题内容。

**Comment by ivye2020** [comment]
报名~

**Comment by lijiangsheng1** [comment]
开源之道Talking 不会谈论具体的细节啊，如果你对CHAOSS 的细节感兴趣，建议参与其日常的邮件列表、在线meeting，CHAOSS Community非常活跃。

**Comment by lijiangsheng1** [comment]
更新下会议信息。请添加到自己的Calendar

适 兕 邀请您参加预先安排的 Zoom 会议。

主题：开源项目的定量和定性分析—— 以CHAOSS 为例 
时间：2020年4月25日 09:00 上午 北京，上海

加入 Zoom 会议
https://zoom.com.cn/j/831035995

会议 ID：831 035 995

手机一键拨号
+16465588656,,831035995# 美国 (纽约)
+14086380968,,831035995# 美国 (圣何塞)

根据您的位置拨号
        +1 646 558 8656 美国 (纽约)
        +1 408 638 0968 美国 (圣何塞)
会议 ID：831 035 995
查找本地号码：https://zoom.com.cn/u/ic4dTWiRgw

**Comment by genedna** [comment]
可以报名旁听么？

**Comment by ZoomQuiet** [comment]
> 更新下会议信息。请添加到自己的Calendar
> 
> 适 兕 邀请您参加预先安排的 Zoom 会议。
> 
> 主题：开源项目的定量和定性分析—— 以CHAOSS 为例
> 时间：2020年4月25日 09:00 下午 北京，上海
> 
> 加入 Zoom 会议
> https://zoom.com.cn/j/831035995
> 
> 会议 ID：831 035 995
> 

是也乎,(￣▽￣)

这个时间刚好和长期预约的一个会议冲突, 只能下半场了...

**Comment by ZoomQuiet** [comment]
> 可以报名旁听么？

@genedna 是也乎,(￣▽￣)

马道长 ,可以先将意见用文字回复到这儿, 也就等于云参与了

**Comment by genedna** [comment]
> 
> 
> > 可以报名旁听么？
> 
> @genedna 是也乎,(￣▽￣)
> 
> 马道长 ,可以先将意见用文字回复到这儿, 也就等于云参与了

我现在对这个没啥头绪，写不出来啥~~

**Comment by king-gao** [comment]
道长，搬个小椅子，或者坐我腿上

发件人：Quanyi Ma <notifications@github.com>
收件人：OCselected/ttoos <ttoos@noreply.github.com>
抄 送：Gaokun (King) <king.gao@huawei.com>;Mention <mention@noreply.github.com>
时 间：2020-04-08 15:57:48
主 题：Re: [OCselected/ttoos] 【开源之道Talking】4月：开源项目的定量和定性分析—— 以CHAOSS 为例 (#79)


可以报名旁听么？

@genedna<https://github.com/genedna> 是也乎,(￣▽￣)

马道长 ,可以先将意见用文字回复到这儿, 也就等于云参与了

我现在对这个没啥头绪，写不出来啥~~

**Comment by lijiangsheng1** [comment]
非常欢迎大驾光临！ @genedna

**Comment by lijiangsheng1** [comment]
http://peerproduction.net/issues/issue-13-open/news-from-nowhere/open-community-health-workshop-report/ 

该论文可以作为探讨的指南。另外文中提到的方法论也值得推荐：

Basili, V. R. (1992). Software modeling and measurement: the Goal/Question/Metric paradigm. Retrieved from https://drum.lib.umd.edu/bitstream/handle/1903/7538/?sequence=1

**Comment by rootsongjc** [comment]
我曾经对这个项目有一定时间的研究，想参加下。但是我每周六晚 8 点还有个社区会议，不知道 9 点能否参与。

**Comment by lijiangsheng1** [comment]
@rootsongjc  把你想讨论的问题列几个。这样可能即使你后半段参与进来，也不耽误任何。

**Comment by rootsongjc** [comment]
我想到的关于 Chaoss 项目的一些问题：

- Chaoss 衡量的开源项目的活跃度的标准是否合理，是否考虑到不同项目之间的差异性？
- 还有很多是流程问题，对于参与社区人员的身份信息，这些不一定都能获取到，这样就影响到数据完整性

**Comment by genedna** [comment]
> 
> 
> 我想到的关于 Chaoss 项目的一些问题：
> 
>     * Chaoss 衡量的开源项目的活跃度的标准是否合理，是否考虑到不同项目之间的差异性？
> 
>     * 还有很多是流程问题，对于参与社区人员的身份信息，这些不一定都能获取到，这样就影响到数据完整性

我觉得这两个问题并不明确，我细化一下：

- CHAOSS 活跃度指标有没有适用范围，如什么样的指标或者几个指标的组合适于衡量什么类型的项目，或者在项目的什么周期适用于什么指标衡量这些项目？
- 数据不完整是否会造成活跃度指标衡量的偏差，如何修正这个偏差？
