### ISSUE TITLE
【开源之道Talking 】5月主题：本土的hacker哪里找？

### ISSUE THREAD

**Issue by lijiangsheng1** [OCselected/ttoos#80]
来自于开源之道图书共读 WeChat Group的一个周末闲聊：

### 龚仪
> @适兕 我纠正了我去年的一个不够精准的说法：那些能做基础软件（操作系统，数据库等）核心开发的人，不能简单的用developer来表述，必须用hacker才是精准的！这种人是稀有的！所以，我还是想做一件事情：寻找中国的hacker！

### 适兕
> [握手][握手][握手] 这也和我对community理解为共同体，而不是消费者社团有异曲同工之妙！
不过寻找中国的hacker这个事情是不可能了，因为从来没有存在过。应该将精力放在培养上。（尽管这个论断有点受挫，但仍然是乐观的。）

### Zoom.Quiet 大妈
> 怎么可能, 那些进入 M$/IBM/Google/Facebook 们的高级工程师们,
> 都是严格意义上的 Hacker 哪...
> 更别说 李大维 们, 在各位领域的 Hacker 从来没有间断过,
> 比如说 窦唯 张楚 们, 不就是音乐界的 Hacker?
> 如果 Hacker 仅仅是在开源技术社区中,
>那么, 就是对 Hacker 本身的误解

### 姜宁
> 我心目中的Hacker是当遇到问题，能利用自己的技能来解决这些问题的人。

### 卫Sir
> 我个人觉得，黑客的显著特点是对科学对技术有着非常浓厚兴趣的人，他们的乐趣是做一个很fancy或者说让人感到很有意思的东西，在软件这个领域，hacker的乐趣主要是编码，通过巧妙构思和精美的设计，做一个普通大众力所不能及的新东西。从而获得非凡的高峰体验。相比之下，hacker觉得和人打交道实在是乏味的打紧，而且由于自身沉溺思考的独有的谨慎内向敏感特质，使得他们更不愿意和人打交道，所以呈现出一种书呆子甚至孤僻的外在表现。（随手想到这几点，尚不完善。）
> 黑客是一种写在基因里的人格类型，这种人有一种喜欢钻研和穷尽的内在倾向，喜欢格物致知，喜欢优美的逻辑，喜欢精心设计一个东西，他们常常做出一般人做不出来的难题、写出一般人写不出来的文章、代码、实现一般人搞不定的功能，突破一般人突破不了的防线（cracker），创造出一般人搞不出来的奇迹（从这个意义上讲，魔术师算一种黑客），他们以此为乐、以此自豪，并以此建立起自己的尊严。

~~~~~~~~~~~~~~~~~~~

既然这个话题令人着迷，我们不妨让更多的人知道，有人对此很着迷。

**Comment by lijiangsheng1** [comment]
[Hacker 文化 ](https://en.wikipedia.org/wiki/Hacker_culture) 的全方位解读。

**Comment by lijiangsheng1** [comment]
目前想到的议题：
0、各位嘉宾对 “Hacker” 的理解。
1、 在自由/开源软件的历史上，Hacker ethics 曾起到了非常重要的影响和作用，各位的对此是如何理解的？
2、 如果加上特殊的地缘政治、文化、历史的话，在本土环境下如何理解？
3、通常情况下，为什么需要和信息技术犯罪撇清关系？
4、开源之道倡导的是“craftman”即匠人，有多本书籍的共读都指向了这个，有何区别？

**Comment by ZoomQuiet** [comment]
是也乎,(￣▽￣)

俺现在, 如果没变化, 每周只有周4有空了...

如果约, 盼望是周四晩大家方便的时间.
